/*
 * Project: UrbanEcho - TinyML Urban Soundscape Monitor
 * Hardware: ESP32 WROOM + INMP441 I2S Microphone
 * Framework: Arduino (ESP32 Core) + Edge Impulse
 * Network: Wi-Fi HTTP POST Integration
 */

#include <driver/i2s.h>
#include <WiFi.h>
#include <HTTPClient.h>

// Set this to the exact header generated by Edge Impulse export, for example:
// "my_project_inferencing.h"
#ifndef EI_PROJECT_INFERENCING_HEADER
#define EI_PROJECT_INFERENCING_HEADER "urban_echo_inferencing.h"
#endif

#if __has_include(EI_PROJECT_INFERENCING_HEADER)
#include EI_PROJECT_INFERENCING_HEADER
#elif __has_include(<bhargav_2007_project_1_inferencing.h>)
#include <bhargav_2007_project_1_inferencing.h>
#elif __has_include(<bhargav-2007-project-1_inferencing.h>)
#include <bhargav-2007-project-1_inferencing.h>
#elif __has_include(<urban-echo_inferencing.h>)
#include <urban-echo_inferencing.h>
#elif __has_include(<urban_echo_inferencing.h>)
#include <urban_echo_inferencing.h>
#else
#error "Edge Impulse inferencing header not found. In Arduino IDE, install your exported Edge Impulse library (.zip), then set EI_PROJECT_INFERENCING_HEADER to the generated *_inferencing.h filename."
#endif

// --- Wi-Fi & Network Credentials ---
const char* WIFI_SSID     = "Bhargav";
const char* WIFI_PASSWORD = "radheradhe";
// Set this to your laptop/PC IPv4 on the same Wi-Fi as ESP32, for example:
// http://192.168.1.100:3000/api/upload
const char* SERVER_URL    = "http://192.168.1.100:3000/api/upload";

// --- Hardware Pin Definitions ---
#define I2S_SCK_PIN     26 // BCLK
#define I2S_WS_PIN      25 // LRC
#define I2S_SD_PIN      33 // Data In
#define I2S_PORT        I2S_NUM_0

// --- Audio Specifications ---
#define SAMPLE_RATE     16000
int16_t sampleBuffer[EI_CLASSIFIER_RAW_SAMPLE_COUNT];

/**
 * @brief Initialize Wi-Fi connection
 */
void setup_wifi() {
    Serial.print("Connecting to Wi-Fi: ");
    Serial.println(WIFI_SSID);
    
    WiFi.mode(WIFI_STA); // Set ESP32 as a standard Wi-Fi station
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    
    int retries = 0;
    while (WiFi.status() != WL_CONNECTED && retries < 20) {
        delay(500);
        Serial.print(".");
        retries++;
    }
    
    if(WiFi.status() == WL_CONNECTED) {
        Serial.println("\nWi-Fi Connected!");
        Serial.print("IP Address: ");
        Serial.println(WiFi.localIP());
    } else {
        Serial.println("\nFailed to connect to Wi-Fi. Operating in offline mode.");
    }
}

/**
 * @brief Initialize the I2S peripheral with DMA buffering
 */
void setup_i2s() {
    i2s_config_t i2s_config = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),
        .sample_rate = SAMPLE_RATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
        .communication_format = i2s_comm_format_t(I2S_COMM_FORMAT_STAND_I2S),
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 8,
        .dma_buf_len = 1024,
        .use_apll = false,
        .tx_desc_auto_clear = false,
        .fixed_mclk = 0
    };

    i2s_pin_config_t pin_config = {
        .bck_io_num = I2S_SCK_PIN,
        .ws_io_num = I2S_WS_PIN,
        .data_out_num = I2S_PIN_NO_CHANGE,
        .data_in_num = I2S_SD_PIN
    };

    i2s_driver_install(I2S_PORT, &i2s_config, 0, NULL);
    i2s_set_pin(I2S_PORT, &pin_config);
    i2s_zero_dma_buffer(I2S_PORT);
}

/**
 * @brief Fills the sampleBuffer via DMA
 */
void capture_audio() {
    size_t bytes_read = 0;
    size_t total_bytes_needed = EI_CLASSIFIER_RAW_SAMPLE_COUNT * sizeof(int16_t);
    
    i2s_read(I2S_PORT, (void*)sampleBuffer, total_bytes_needed, &bytes_read, portMAX_DELAY);
}

/**
 * @brief Edge Impulse Signal Wrapper
 */
int microphone_audio_signal_get_data(size_t offset, size_t length, float *out_ptr) {
    if (offset + length > EI_CLASSIFIER_RAW_SAMPLE_COUNT) return -1;
    for (size_t i = 0; i < length; i++) {
        out_ptr[i] = (float)sampleBuffer[offset + i];
    }
    return 0;
}

/**
 * @brief Sends an HTTP POST request with the classification data
 */
void send_data_to_dashboard(const char* highest_class, float confidence) {
    // Only attempt to send if Wi-Fi is connected
    if (WiFi.status() == WL_CONNECTED) {
        HTTPClient http;
        http.begin(SERVER_URL);
        http.addHeader("Content-Type", "application/json");

        // Format a JSON string to send
        char jsonPayload[128];
        snprintf(jsonPayload, sizeof(jsonPayload), "{\"event_type\":\"%s\", \"confidence\":%.2f}", highest_class, confidence);

        Serial.printf("Uploading via Wi-Fi: %s\n", jsonPayload);
        
        int httpResponseCode = http.POST(jsonPayload);
        if (httpResponseCode > 0) {
            Serial.printf("HTTP Response: %d\n", httpResponseCode);
        } else {
            Serial.printf("HTTP Error: %s\n", http.errorToString(httpResponseCode).c_str());
        }
        http.end(); // Free resources
    } else {
        Serial.println("Wi-Fi disconnected. Cannot send data.");
        // Optional: Call setup_wifi() here to try reconnecting
    }
}


void setup() {
    Serial.begin(115200);
    while (!Serial);
    
    Serial.println("\n--- UrbanEcho: Edge-AI + Wi-Fi Booting ---");
    
    setup_wifi();
    setup_i2s();
    delay(1000); // Allow mic to stabilize
    
    Serial.println("System Ready. Starting Continuous Inference.");
}

void loop() {
    // 1. Capture Audio
    capture_audio();

    // 2. Setup AI signal
    signal_t signal;
    signal.total_length = EI_CLASSIFIER_RAW_SAMPLE_COUNT;
    signal.get_data = &microphone_audio_signal_get_data;

    // 3. Run Inference
    ei_impulse_result_t result = { 0 };
    EI_IMPULSE_ERROR res = run_classifier(&signal, &result, false);
    if (res != EI_IMPULSE_OK) return;

    // 4. Find the most likely sound classification
    float highest_confidence = 0.0;
    const char* highest_label = "Unknown";

    for (size_t ix = 0; ix < EI_CLASSIFIER_LABEL_COUNT; ix++) {
        if (result.classification[ix].value > highest_confidence) {
            highest_confidence = result.classification[ix].value;
            highest_label = result.classification[ix].label;
        }
    }

    Serial.printf("Detected: %s (%.2f%%)\n", highest_label, highest_confidence * 100.0);

    // 5. Smart Wi-Fi Triggering Logic
    // We only send data if the AI is highly confident (>80%), to save battery and bandwidth
    if (highest_confidence > 0.80) {
        // Prevent spamming: only send if it's an important event (e.g., Anomaly or Anthropogenic Noise)
        // You can customize this logic based on your custom Edge Impulse classes
        if (strcmp(highest_label, "Traffic_Noise") == 0 || strcmp(highest_label, "Anomaly") == 0) {
            send_data_to_dashboard(highest_label, highest_confidence);
        }
    }
}